```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(sf)
library(ggplot2)
library(ggsflabel)
library(ggspatial)
library(knitr)
library(kableExtra)
library(TDX)
library(DT)

windowsFonts(A=windowsFont("微軟正黑體"))

app_id = '8f35504e01eb4a43abfd41c920955690'
app_key = 'H9MfljykHDeGiifyr2zKJ0XsKFQ'
```

# **公車運輸資料**
公車係包含公路客運（一般公路客運、國道公路客運）與市區客運。後續的函式中皆須設定縣市之參數（`county=`），請參照`TDX_County`表格，縣市名稱與其相對應之代碼臚列如下。另請注意，若欲回傳公路客運之資料，`county=`之參數請設定為「`Intercity`」。  

```{r TDX_County, echo=T, eval=F}
TDX_County
```

```{r TDX_Railway_table, echo=F, eval=T}
TDX_County_temp=TDX_County
colnames(TDX_County_temp)=c("縣市名稱","縣市代碼")
kable(TDX_County_temp, booktabs=T)%>%
  kable_styling(bootstrap_options=c("striped", "hover"), font_size=14)%>%
  column_spec(1, bold=T)%>%
  row_spec(0, bold=T, color="white", background="#7B7B7B")
```

此外本資料之下載皆須利用 API 金鑰，故函式中須輸入`app_id=`與`app_key=`兩參數，亦即在 [1.6.2 API 金鑰申請](#api-金鑰申請)的 APP ID 與 APP Key。  

公車運輸資料中提供路線站點、路線線型、班表等資料。  



## 公車路線站點資料
<font color="#484891" size="4"><u>**◎ 資料概述**</u></font>  
回傳結果為公車路線站點的屬性資料，欄位包括（子）路線名稱、（子）路線代碼、方向、站點名稱、站點代碼、站序、經緯度等資料。  

<font color="#484891" size="4"><u>**◎ 函式參數**</u></font>  
```{r Bus_StopOfRoute_code, echo=T, eval=F}
Bus_StopOfRoute(app_id, app_key, county, dtype="text", out=FALSE)
```

```{r Bus_StopOfRoute_table, echo=F, eval=T}
TDX_table=data.frame(parameter=c("`app_id=`", "`app_key=`", "`county=`", rep("`dtype=`", 2), rep("`out=`", 3)),
                     must=c(rep("必填參數", 3), rep("選填參數", 5)),
                     func=c("[金鑰 APP ID]","[金鑰 APP Key]","縣市代碼", rep("回傳的資料型態", 2), rep("匯出資料之路徑", 3)),
                     details=c("[1.6.2 API 金鑰申請](#api-金鑰申請)的 APP ID","[1.6.2 API 金鑰申請](#api-金鑰申請)的 APP Key","請參照`TDX_County`表格，若為公路客運，請填入`Intercity`","`text`：純文字形式，其資料型態屬`data.frame` [**預設值**]","`sf`：地理資料形式，其資料型態屬`sf`","`FALSE`：不匯出資料至本機 [**預設值**]" ,"若回傳的資料型態為「`text`」：路徑必須含有`.csv`或`.txt`", "若回傳的資料型態為「`sf`」：路徑必須含有`.shp`"))

colnames(TDX_table)=c("參數","必選填","功能","參數設定值")

kable(TDX_table, booktabs=T)%>%
  kable_styling(bootstrap_options=c("striped", "hover"), font_size=14)%>%
  column_spec(1, bold=T)%>%
  column_spec(1:4, background="white")%>%
  row_spec(0, bold=T, color="white", background="#8E8E8E")%>%
  collapse_rows(columns=c(1:3))
```

<font color="#484891" size="4"><u>**◎ 程式碼撰寫範例**</u></font>  


## 公車路線線型資料




## 公車班表資料



